#!/usr/bin/env bash
# pipeline.sh: Full workflow automation for pretrain → finetune → GradCAM ROI → pretrain (ROI) → finetune (ROI)
set -euo pipefail

# --- CONFIGURABLE PARAMETERS ---
BACKBONES_CSV="gastronet,dinov3"
PRETRAIN_LOSS="suppro"
FINETUNE_LOSS="ce"
HEAD_TYPE="linear"
BATCH_SIZE=32
PRETRAIN_EPOCHS=20
FINETUNE_EPOCHS=20
LR=1e-4
WARMUP_EPOCHS=3
SEED=42
SAVE_DIR="./checkpoints/pipeline"
ROI_RECORDS_PATH="./checkpoints/pipeline/gradcam_rois.json"

# --- 1. INITIAL PRETRAINING ---
echo "[1/5] Pretraining (no ROI)"
EXPERIMENT_ID="pipeline_pretrain" ENABLE_ROI_GUIDANCE=0 RUN_COMPARISON_BASELINE=0 SAVE_DIR="$SAVE_DIR" BACKBONES_CSV="$BACKBONES_CSV" PRETRAIN_LOSS="$PRETRAIN_LOSS" FINETUNE_LOSS="$FINETUNE_LOSS" HEAD_TYPE="$HEAD_TYPE" BATCH_SIZE="$BATCH_SIZE" PRETRAIN_EPOCHS="$PRETRAIN_EPOCHS" FINETUNE_EPOCHS="$FINETUNE_EPOCHS" LR="$LR" WARMUP_EPOCHS="$WARMUP_EPOCHS" SEED="$SEED" ./main.sh

# --- 2. FINETUNE FOR GRADCAM ROI GENERATION ---
echo "[2/5] Finetuning for GradCAM ROI generation (20 epochs)"
EXPERIMENT_ID="pipeline_finetune1" ENABLE_ROI_GUIDANCE=0 RUN_COMPARISON_BASELINE=0 SAVE_DIR="$SAVE_DIR" BACKBONES_CSV="$BACKBONES_CSV" PRETRAIN_LOSS="$PRETRAIN_LOSS" FINETUNE_LOSS="$FINETUNE_LOSS" HEAD_TYPE="$HEAD_TYPE" BATCH_SIZE="$BATCH_SIZE" PRETRAIN_EPOCHS="$PRETRAIN_EPOCHS" FINETUNE_EPOCHS="$FINETUNE_EPOCHS" LR="$LR" WARMUP_EPOCHS="$WARMUP_EPOCHS" SEED="$SEED" ./main.sh

# --- 3. SAVE GRADCAM ROIS ---
echo "[3/5] Saving GradCAM ROIs"
# (Assumes main.sh saves GradCAM ROIs automatically after finetune. If not, add code here to extract and save ROIs.)

# --- 4. SECOND PRETRAINING USING GRADCAM ROIS ---
echo "[4/5] Pretraining using GradCAM ROIs"
EXPERIMENT_ID="pipeline_pretrain_roi" ENABLE_ROI_GUIDANCE=1 RUN_COMPARISON_BASELINE=0 SAVE_DIR="$SAVE_DIR" BACKBONES_CSV="$BACKBONES_CSV" PRETRAIN_LOSS="$PRETRAIN_LOSS" FINETUNE_LOSS="$FINETUNE_LOSS" HEAD_TYPE="$HEAD_TYPE" BATCH_SIZE="$BATCH_SIZE" PRETRAIN_EPOCHS="$PRETRAIN_EPOCHS" FINETUNE_EPOCHS="$FINETUNE_EPOCHS" LR="$LR" WARMUP_EPOCHS="$WARMUP_EPOCHS" SEED="$SEED" PRETRAIN_ROI_RECORDS_PATH="$ROI_RECORDS_PATH" ./main.sh

# --- 5. FINAL FINETUNING WITH ROI GUIDANCE ---
echo "[5/5] Final finetuning with ROI guidance"
EXPERIMENT_ID="pipeline_finetune2_roi" ENABLE_ROI_GUIDANCE=1 RUN_COMPARISON_BASELINE=0 SAVE_DIR="$SAVE_DIR" BACKBONES_CSV="$BACKBONES_CSV" PRETRAIN_LOSS="$PRETRAIN_LOSS" FINETUNE_LOSS="$FINETUNE_LOSS" HEAD_TYPE="$HEAD_TYPE" BATCH_SIZE="$BATCH_SIZE" PRETRAIN_EPOCHS="$PRETRAIN_EPOCHS" FINETUNE_EPOCHS="$FINETUNE_EPOCHS" LR="$LR" WARMUP_EPOCHS="$WARMUP_EPOCHS" SEED="$SEED" PRETRAIN_ROI_RECORDS_PATH="$ROI_RECORDS_PATH" ./main.sh

echo "Pipeline complete."
