#!/usr/bin/env bash

# SMOTE finetuning configuration.
# Override any of these with environment variables before launching `main.sh`.

CLASSIFIER_INPUT="${CLASSIFIER_INPUT:-pooled}"
FINETUNE_TRAIN_MODE="${FINETUNE_TRAIN_MODE:-last_block}"

ENABLE_SMOTE_FILTER="${ENABLE_SMOTE_FILTER:-0}"
ENABLE_SMOTE_KNN_FILTER="${ENABLE_SMOTE_KNN_FILTER:-0}"
ENABLE_SMOTE_REFINE="${ENABLE_SMOTE_REFINE:-0}"

SMOTE_FEATURE_SPACE="${SMOTE_FEATURE_SPACE:-pooled}"
SMOTE_NEIGHBORS="${SMOTE_NEIGHBORS:-3}"
SMOTE_SAMPLING_STRATEGY="${SMOTE_SAMPLING_STRATEGY:-minority}"
SMOTE_SYNTHETIC_RATIO="${SMOTE_SYNTHETIC_RATIO:-0.10}"
SMOTE_WARMSTART_EPOCHS="${SMOTE_WARMSTART_EPOCHS:-3}"

SMOTE_REFINE_STEPS="${SMOTE_REFINE_STEPS:-3}"
SMOTE_REFINE_STEP_SIZE="${SMOTE_REFINE_STEP_SIZE:-0.01}"

SMOTE_ENERGY_EPOCHS="${SMOTE_ENERGY_EPOCHS:-25}"
SMOTE_ENERGY_LR="${SMOTE_ENERGY_LR:-1e-3}"
SMOTE_ENERGY_WEIGHT_DECAY="${SMOTE_ENERGY_WEIGHT_DECAY:-1e-4}"
SMOTE_ENERGY_BATCH_SIZE="${SMOTE_ENERGY_BATCH_SIZE:-256}"
SMOTE_ENERGY_HIDDEN_DIM="${SMOTE_ENERGY_HIDDEN_DIM:-256}"
SMOTE_ENERGY_LAYERS="${SMOTE_ENERGY_LAYERS:-2}"
SMOTE_ENERGY_DROPOUT="${SMOTE_ENERGY_DROPOUT:-0.1}"
SMOTE_ENERGY_QUANTILE="${SMOTE_ENERGY_QUANTILE:-0.80}"
SMOTE_ENERGY_NOISE_STD="${SMOTE_ENERGY_NOISE_STD:-0.15}"
SMOTE_ENERGY_NOISE_COPIES="${SMOTE_ENERGY_NOISE_COPIES:-2}"
SMOTE_ENERGY_MAJORITY_RATIO="${SMOTE_ENERGY_MAJORITY_RATIO:-1.0}"
SMOTE_ENERGY_REFINE_ANCHOR_WEIGHT="${SMOTE_ENERGY_REFINE_ANCHOR_WEIGHT:-5.0}"
SMOTE_ENERGY_REFINE_MARGIN_WEIGHT="${SMOTE_ENERGY_REFINE_MARGIN_WEIGHT:-2.0}"
SMOTE_ENERGY_REFINE_TARGET_MARGIN="${SMOTE_ENERGY_REFINE_TARGET_MARGIN:-0.05}"

SMOTE_KNN_NEIGHBORS="${SMOTE_KNN_NEIGHBORS:-}"
SMOTE_KNN_SUPPORT_QUANTILE="${SMOTE_KNN_SUPPORT_QUANTILE:-0.50}"
SMOTE_KNN_MINORITY_PURITY="${SMOTE_KNN_MINORITY_PURITY:-1.0}"
SMOTE_KNN_MARGIN="${SMOTE_KNN_MARGIN:-0.02}"
SMOTE_KNN_CENTER_AWARE="${SMOTE_KNN_CENTER_AWARE:-0}"
